version: "3"

services:
  web:
    build:
      context: .
    container_name: segments
    command: gunicorn --error-logfile - --access-logfile - --workers 3 --bind 0:8000 config.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
      - ./data:/data
    environment:
      - DEBUG=1
      - DATABASE_URL=sqlite:////data/db.sqlite
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - CSRF_TRUSTED_ORIGINS=127.0.0.1
      - STATICFILES_DIR=/data/staticfiless
