# Generated by Django 3.1.5 on 2021-01-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_add_segment_color_type_order_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('name', models.CharField(
                    max_length=30, unique=True, verbose_name='Компания',
                )),
                ('slug', models.SlugField()),
                ('image', models.ImageField(
                    upload_to='images', verbose_name='Лого',
                )),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={
                'ordering': ['-created'],
                'verbose_name': 'Отрезок',
                'verbose_name_plural': 'Отрезки',
            },
        ),
        migrations.AlterField(
            model_name='colortype',
            name='name',
            field=models.CharField(
                max_length=15, unique=True, verbose_name='Фактура',
            ),
        ),
        migrations.AlterField(
            model_name='ordernumber',
            name='name',
            field=models.CharField(
                max_length=15, unique=True, verbose_name='Номер заказа',
            ),
        ),
        migrations.AlterField(
            model_name='rack',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Расположение'),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('name', 'type')},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('name', models.CharField(
                    max_length=30, verbose_name='Название цеха',
                )),
                ('slug', models.SlugField()),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sections',
                    to='segments.company',
                    verbose_name='Компания',
                )),
                ('excluded_colors', models.ManyToManyField(
                    blank=True,
                    related_name='sections',
                    to='segments.ColorType',
                    verbose_name='Исключить фактуры',
                )),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='section',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='racks',
                to='segments.section',
                verbose_name='Цех',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('name', 'section')},
        ),
    ]
