# Generated by Django 3.2.9 on 2021-11-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0005_disable_null_for_color_models_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={
                'ordering': ('type', 'name'),
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
