# Generated by Django 3.1.5 on 2021-01-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.CharField(blank=True, max_length=15)),
                ('color', models.CharField(blank=True, max_length=15)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('square', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('order_number', models.CharField(blank=True, max_length=15)),
                ('rack', models.CharField(blank=True, max_length=20)),
                ('defect', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'segment',
            },
        ),
    ]
