# Generated by Django 3.1.5 on 2021-01-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_add_color_type_order'),
    ]

    operations = [
    ]
