# Generated by Django 4.1.5 on 2023-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0006_alter_color_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AddField(
            model_name='company',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
