---
- name: Deploy application
  hosts: web
  gather_facts: no

  tasks:
  - name: Update project from git
    ansible.builtin.git:
      repo: "{{ repo_url }}/{{ repo }}.git"
      dest: "{{ repo_dir }}"
  - name: Install specified python requirements
    ansible.builtin.pip:
      virtualenv: "{{ venv_dir }}"
      requirements: "{{ repo_dir }}/requirements.txt"
  - name: django collectstatic
    community.general.django_manage:
      command: collectstatic
      project_path: "{{ project_dir }}"
      virtualenv: "{{ venv_dir }}"
  - name: django migrate
    community.general.django_manage:
      command: migrate
      project_path: "{{ project_dir }}"
      virtualenv: "{{ venv_dir }}"
  - name: Restart service
    ansible.builtin.systemd:
      state: restarted
      name: segments.service
    become: yes
